# Generated by Django 2.2.4 on 2019-08-19 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionario',
            new_name='Produto',
        ),
    ]
